### ISSUE TITLE
Incompatibility with phpstan/phpstan v1.11.3

### ISSUE THREAD

**Issue by lentex** [pestphp/pest-plugin-type-coverage#29]
Hello,
I've updated my dependencies in my project which unfortunately broke the type coverage.
I've found the reason for that:

The latest **pestphp/pest-plugin-type-coverage** (v2.8.2) is incompatible with the latest version of **phpstan/phpstan** ([v1.11.3](https://github.com/phpstan/phpstan/releases/tag/1.11.3)) as they introduced a breaking change in the `NodeScopeResolver`:

See https://github.com/phpstan/phpstan-src/pull/3089

The constructor now has another parameter. Unfortunately named arguments would not help here as the new parameter is mandatory.

**My temporary fix is to downgrade to v.11.2**

Would be great if this would be fixed (I really don't know the internals well enough to be able to submit a PR 😞 )

**Comment by tomloprod** [comment]
@lentex Yesterday, I created a small PR to address this. I hope Nuno or another collaborator can validate it 😊

https://github.com/pestphp/pest-plugin-type-coverage/pull/28

**Comment by lentex** [comment]
@tomloprod thx for pointing out this PR. sorry for being stupid and not checking the existing PRs beforehand 🤦‍♂️

**Comment by tomloprod** [comment]
> @tomloprod thx for pointing out this PR. sorry for being stupid and not checking the existing PRs beforehand 🤦‍♂️ 

Don't worry! I just pointed out the PR in case it can temporarily help you work until Nuno decides how to proceed. 🙂

Have a good weekend!

**Comment by lentex** [comment]
all good. i've just downgraded to v1.11.2 which is fine for now!

**Comment by tomloprod** [comment]
@lentex I think this issue can be closed now, since there is already compatibility with version 1.11.3 👍🏻

**Comment by lentex** [comment]
Yes, I can confirm that the latest version is compatible with the latest phpstan version.
Thank you very much! 🙏
