### ISSUE TITLE
CI broken, we need release

### ISSUE THREAD

**Issue by faissaloux** [pestphp/pest-plugin-type-coverage#31]
Hello @nunomaduro this issue is fixed on https://github.com/pestphp/pest-plugin-type-coverage/commit/147f8b6d5dc180a756aa694d34f606050b823c71, can you please tag it our CI is failing because of this.

![image](https://github.com/user-attachments/assets/bab59538-f60b-4ab8-a11d-5e3a47c98e7f)

**Comment by jeremieflahaut** [comment]
Hello every body i have the same problem with 

"pestphp/pest": "^2.25", (2.34.9)
"pestphp/pest-plugin-type-coverage": "^2.8", (2.8.4)
"phpstan/phpstan": "1.11.8", (1.11.8)

Did I miss something ?

**Comment by RhysLees** [comment]
Also getting this issue @nunomaduro all out ci pipelines are broken, is there a fix

**Comment by faissaloux** [comment]
> Hello every body i have the same problem with
> 
> "pestphp/pest": "^2.25", (2.34.9) "pestphp/pest-plugin-type-coverage": "^2.8", (2.8.4) "phpstan/phpstan": "1.11.8", (1.11.8)
> 
> Did I miss something ?


You need to set `phpstan/phpstan` to maximum `v1.11.7`

```json
"phpstan/phpstan": "1.11.7"
```

**Comment by ahtinurme** [comment]
Seems that the new phpstan release has fixed this issue, so please close @nunomaduro
