### ISSUE TITLE
 Unknown option "--type-coverage".

### ISSUE THREAD

**Issue by CerealKiller97** [pestphp/pest-plugin-type-coverage#8]
Hello there,

I've started using this plugin, and I have bumped into a problem. On my local machine it works good, but on GH Actions it does not.

Command I run on GH action is: 
```sh
 pest --type-coverage --min=98
```

INFO  Unknown option "--type-coverage".

**Comment by gehrisandro** [comment]
Hi @CerealKiller97 

This should work fine.
Are you sure the plugin is properly installed during GH action?

**Comment by CerealKiller97** [comment]
> Hi @CerealKiller97 
> 
> This should work fine.
> Are you sure the plugin is properly installed during GH action?

Yes it's installed on GH actions.

**Comment by gehrisandro** [comment]
Can you please provide your composer.lock file?

**Comment by CerealKiller97** [comment]
@gehrisandro Here you go. https://pastebin.com/ef5TmM2x
