### ISSUE TITLE
Ignore next line

### ISSUE THREAD

**Issue by bramvanrijswijk** [pestphp/pest-plugin-type-coverage#9]
First of all, thanks for creating this package, it helps a lot.
It'd be a great addition to ignore lines. Hope to see that soon! 🙏

**Comment by fsamapoor** [comment]
Really looking forward to seeing these related PRs get merged:
#5 #7

**Comment by bramvanrijswijk** [comment]
Any updates on this, @nunomaduro?

**Comment by devajmeireles** [comment]
Hey, @bramvanrijswijk . Thanks for your feature request! 

Today we had a new release introducing this new feature.

To preserve better organization, I will close this edition. Feel free to open a new issue whenever necessary.
